### ISSUE TITLE
No graphql type is generated (maybe related to gatsby-plugin-ts-config)

### ISSUE THREAD

**Issue by openscript** [d4rekanguok/gatsby-typescript#101]
**Describe the bug**
After I migrated all Gatsby configuration to TypeScript with the help of gatsby-plugin-ts-config no more graphql types are generated.

**To Reproduce**
I've pushed everything to: https://github.com/openscript/obin.ch.

1. Clone the repo
1. Install it's dependencies
1. Run `yarn dev`
1. No type definitions are produced

**Environment (please complete the relevant info):**
- Linux 5.7.10-arch1-1 SMP PREEMPT
- Gatsby version 2.23.20
- Typescript version 3.9.6

**Additional context**
I don't know, if this is related to gatsby-plugin-ts-config (ping @Js-Brecht), because before the migration it was working well. Any help or hint is appreciated.

**Comment by openscript** [comment]
My configuration `gatsby-config.ts` looks as follows:
```
import { ITSConfigFn } from 'gatsby-plugin-ts-config';

const configuration: ITSConfigFn<'config'> = ({ projectRoot }) => ({
  siteMetadata: {
    title: 'r.obin.ch',
    license: 'AGPL-3.0',
    url: 'https://r.obin.ch',
    author: {
      name: 'Robin',
      email: 'r@obin.ch'
    }
  },
  plugins: [
    // Plugins
    'gatsby-plugin-emotion',
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sharp',
    'gatsby-plugin-svgr',
    {
      resolve: 'gatsby-plugin-ts',
      options: {
        codegen: true,
        fileName: `${projectRoot}/gatsby-graphql.ts`,
        documentPaths: [
          `${projectRoot}/src/**/*.{ts,tsx}`,
          `${projectRoot}/node_modules/gatsby-*/**/*.js`,
          `${projectRoot}/gatsby-node.ts`,
        ],
      }
    },
    {
      resolve: 'gatsby-plugin-i18n',
      options: {
        langKeyDefault: 'en',
        useLangKeyLayout: false,
        prefixDefault: false
      }
    },

    // Sources
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'content',
        path: `${projectRoot}/src/content`
      }
    },

    // Transformers
    'gatsby-transformer-sharp',
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          'gatsby-remark-copy-linked-files',
          {
            resolve: 'gatsby-remark-images',
            options: {
              maxWidth: 1140,
              quality: 90,
              linkImagesToOriginal: false
            }
          }
        ]
      }
    }
  ]
});

export default configuration;
```

The configuration of the `gatsby-plugin-ts` doesn't have any effect. If I remove it the project still builds. It seems to be ignored completely. Has it something to do with the per default enabled `gatsby-plugin-typescript`?

**Comment by Js-Brecht** [comment]
Hello @openscript, first thing I've noticed is that `gatsby-plugin-graphql-codegen` does not account for absolute paths when dealing with `documentPaths` and `filename`.  It uses Gatsby's `program.directory` to join project root with the paths defined in the config.  When absolute paths are used, it results in them being doubled up: `/path/to/project/path/to/project/gatsby-graphql.ts`

This config got me further:
```js
    {
      resolve: 'gatsby-plugin-ts',
      options: {
        codegen: true,
        fileName: `gatsby-graphql.ts`,
        documentPaths: [
          `src/**/*.{ts,tsx}`,
          `node_modules/gatsby-*/**/*.js`,
          `gatsby-node.ts`,
        ],
      }
    },
```

I am now encountering the error `Error: Unexpected schema type: BooleanQueryOperatorInput`.  Tracing it down now, so I will get back to you.

**Comment by Js-Brecht** [comment]
Okay, the final issue is here in your `package.json`:

```
"dependencies": {
   ...,
    "graphql": "^15.2.0",
   ...,
}
```

Gatsby uses `graphql@14.7.0`, and because you have that in your dependencies, `graphql@15.2.0` is being hoisted and used by your project (therefore, it is being used by `gatsby-plugin-graphql-codegen`, and by extension, `@graphql-codegen/*`.  Meanwhile, Gatsby is using a completely different instance (and major version!) in its local `node_modules` directory.

By getting rid of that dependency, I was able to build your project successfully, and types were correctly generated.

**Comment by Js-Brecht** [comment]
> The configuration of the `gatsby-plugin-ts` doesn't have any effect. If I remove it the project still builds. It seems to be ignored completely. Has it something to do with the per default enabled `gatsby-plugin-typescript`?

About this comment: `gatsby-plugin-ts` will not generally have much affect when transpiling your code, because yes, it is getting hit by `gatsby-plugin-typescript` first.  I recently opened an issue related to this at https://github.com/gatsbyjs/gatsby/issues/26027.

It will, however, still generate the graphql types, because that is a process apart from the transpiling.

It will also do typechecking successfully, since it sets `transpileOnly` to true by default (so it is not concerned with types), and it also sets up `fork-ts-checker-webpack-plugin`.  That runs apart from the transpiling process, too, so it is not affected by babel.

Ultimately, `ts-loader` itself will wind up doing a whole lot of nothing except take up time.  Depending on how exotic your code gets in the future, it may wind up causing new issues by trying to transpile code that's already been hit by babel, though.  Just an FYI.

**Comment by d4rekanguok** [comment]
@Js-Brecht Thank you for digging in & your insight!

**Comment by openscript** [comment]
Hi @Js-Brecht, first of all, thank you for taking the time and looking into my issue.

Unfortunately I couldn't solve my problem. 

1. `.gatsby/gatsby-config.ts` adapted to:

```
...
    {
      resolve: 'gatsby-plugin-ts',
      options: {
        codegen: true,
        fileName: 'graphql-type.ts',
        documentPaths: [
          'src/**/*.{ts,tsx}',
          'node_modules/gatsby-*/**/*.js',
          '.gatsby/gatsby-node.ts',
        ],
      }
    },
...
```

2. Changed the `graphql` dependency in my `package.json`:
```
...
    "graphql": "^14.6.0",
...
```

3. Ran `yarn install`. I've also deleted my `node_modules` and `.cache` before that.
4. Ran `yarn dev` (-> `gatsby develop`).

There is no `graphql-type.ts` created in any place of the project. I've also pushed these changes to the mentioned repo. Do you have an idea what I'm doing wrong? I'm using `yarn 1.22.4`.

**Comment by Js-Brecht** [comment]
Maybe related to https://github.com/gatsbyjs/gatsby/issues/26074

I'm not at a computer right now, so I can't say exactly what's happening, but I'd say try running `gatsby build`.  That should at least generate the types.

**Comment by openscript** [comment]
You are absolutely right with this. I upgraded `gatsby` to `2.24.12` and it works now with `gatsby develop`. Thank you so much!
