### ISSUE TITLE
Release v2.7.2 on npm

### ISSUE THREAD

**Issue by kije** [d4rekanguok/gatsby-typescript#109]
I noticed that the latest released version of this plugin on npm is v2.7.1, but here on github, the latest release is v2.7.2.

I currently have an Issue with my gatsby builds with outdated fork-ts-checker-webpack-plugin used in this plugin, which would be solved with the updated dependencies included in v2.7.2, so I would be happy to see the new version released.

One note, however: I think the dependency upgrade is a breaking change, as the options schema for fork-ts-checker-webpack-plugin have changed in v5, and since the plugin exposes the `forkTsCheckerPlugin` option that gets directly passed to fork-ts-checker-webpack-plugin, users of the plugin that have set these options need to migrate them

**Comment by d4rekanguok** [comment]
Hey @kije, thanks again for your previous work on this repo! The reason why I haven't published 2.7.2 is because I run into an error locally after merging ([see here](https://github.com/d4rekanguok/gatsby-typescript/pull/103#issuecomment-681749401)), but I haven't managed to dig deeper on it and / or check if that's still an issue; Gatsby has released many updates since.

Would you have the time to take a look & see if 2.7.2 indeed resolves your issue? If it does, I will publish it under a major version (thanks for the tip!)

Also, I haven't worked on a Gatsby site for a while — I'm looking for someone to take care of the repo if you're up for it!
